### ISSUE TITLE
README.md specifies setting permissions to logs file to 777

### ISSUE THREAD

**Issue by ghost** [nekromoff/rpi-monitor-dashboard#7]
This is a HUGE NO-NO on Linux and introduces a massive security vulnerability.

**Comment by nekromoff** [comment]
OK, thanks for the report. Your recommendation?

Most of the RPis are expected to not be multiuser, so this is rather theoretical.

**Comment by ghost** [comment]
Hey,

You're not talking about *users* but *processes* - which could be a
worm/malware/virus etc. so never underestimate the risk. Good security also
helps in other ways.

Fortunately, it's easy to fix. Just give the logs directory the *ownership*
of the PHP process - usually the same as your web server, and give *that*
user write permissions; you can also give a *group* access to the directory
if other processes need right to it for read and/or write. Depends on which
processes access the directory.

Regards,
-Andy (cybervegan)

**Comment by nekromoff** [comment]
Thank you, I'll change README accordingly.
